### ISSUE TITLE
Add support for react 19

### ISSUE THREAD

**Issue by emish89** [greatSumini/react-facebook-login#1000]
Hi @greatSumini , are you going to upgrade the project to support react v19?

If you want I can do a PR, there should be no breaking changes.

**Comment by hypecode-tech** [comment]
Yeah also, it breaks the project on react v18.0.2

**Comment by greatSumini** [comment]
sorry for late fix. the new version is just released! https://github.com/greatSumini/react-facebook-login/releases/tag/v3.4.0
