### ISSUE TITLE
Get white page after confirmation and won't close the popup

### ISSUE THREAD

**Issue by confact** [greatSumini/react-facebook-login#238]
Hi,

I am using this to sign in with facebook and I get a white page in the popup after accepting the permission and it won't close and all confirmation don't work and when I close it i get status `loginCancelled` but it was not.

I do use API v13.0

Code to reproduce:
```javascript

const handleResponse = (response) => {
  console.log("response", response)
}

return (
  <FacebookLogin
    appId="{APP_ID}"
    initParams={{
      version: 'v13.0',
      xfbml: true,
    }}
    scope="public_profile,instagram_basic,instagram_manage_insights,pages_read_engagement,pages_show_list"
    onFail={(e) => console.log('error', e)}
    onSuccess={handleResponse}
    onProfileSuccess={handleResponse}
  />
)
 ```
 
 Facebook app only have Facebook login and Instagram app enabled. With correct redirect uri and `Login with the JavaScript SDK` set to Yes.

The page in the popup window get white/gray after clicking `Continue As ...` or `Continue` at the popup

**Comment by confact** [comment]
@greatSumini can you check this please? :)

**Comment by greatSumini** [comment]
Thank you for report!
I will check/fix it soon 👀👀 (in 3 days)

**Comment by greatSumini** [comment]
@confact 
I think it's facebook sdk's internal error.. 
I think it would be difficult to solve this problem right now

**Comment by confact** [comment]
I have sent it in the bug report at facebook, still waiting for response.

**Comment by greatSumini** [comment]
this is related with facebook sdk
