### ISSUE TITLE
I'd like to logout after logged in.

### ISSUE THREAD

**Issue by wann2** [greatSumini/react-facebook-login#3]
After a user logged in facebook using this library, later if I want to logout, then how can I logout?

페이스북 로그인에 대해서는 설명이 되어 있는데 로그아웃 할 때는 어떻게 구현해야 로그아웃을 처리할 수 있는지요?

**Comment by greatSumini** [comment]
It's not implemented yet 😅 . I'll work on it over the weekend! (It'll be added as a parameter for custom render function.)

미구현 상태입니다. 주말중에 작업해보겠습니다! (custom render function의 parameter로 추가될 것 같습니다.)

**Comment by wann2** [comment]
많이 기대됩니다. 대단히 감사합니다.

**Comment by greatSumini** [comment]
Thank you for waiting. Two brand-new features in v2.0.1 can resolve this issue!
1. logout in custom render function's parameter [usage](https://github.com/greatSumini/react-facebook-login#3-facebookclient)
2. FacebookClient.logout [usage](https://github.com/greatSumini/react-facebook-login#3-facebookclient)

기다려주셔서 감사합니다. 이제 v2.0.1에서 새롭게 추가된 두 가지 기능으로 로그아웃할 수 있습니다.
1. custom render function의 logout paramter [예시](https://github.com/greatSumini/react-facebook-login#3-facebookclient)
2. 새로 추가된 FacebookClient의 logout method [예시](https://github.com/greatSumini/react-facebook-login#3-facebookclient)

**Comment by wann2** [comment]
I appreciate it.
