### ISSUE TITLE
Status Cancelled on Production

### ISSUE THREAD

**Issue by DUMBALINYOLO** [greatSumini/react-facebook-login#320]
When on development it is authenticating well but on production it returned status of cancelled I do not know what may be the issue. May you please help

**Comment by greatSumini** [comment]
Hi @DUMBALINYOLO 
Thank you for using this package!

Can i know which os did you test?
and can i get the repository the problem happend?

**Comment by DUMBALINYOLO** [comment]
On development I am using windows, but the project is hosted on linux servers. I just realised it works on browsers like firefox and microsoft edge yet doesnt in google chrome and opera mini. It gives me {authresponse: null, status: 'unknown'} when I try to login. I did try use the facebook sdk directly and I face the same problem and I am starting to feel it may be related to the domain and facebook for on development it works in all browsers
