### ISSUE TITLE
Is there a way to call the Graph API from this library after successful login?

### ISSUE THREAD

**Issue by Jdelbarcogarza** [greatSumini/react-facebook-login#342]
Hello! First of all, thanks for maintaining a library that does this work of handling login for us. Facebook docs on this are really a hassle, especially with newer technologies such as React, integration is not as seamless. 

Now for my question, I was wondering if there is a way inside this library to make get requests to the Graph API. Or should I go straight to the Facebook docs looking for a method that does this?

Sorry if this looks kind of a dumb question. Thanks in advance! :)

**Comment by greatSumini** [comment]
hi @Jdelbarcogarza !!

Unfortunately, this library only handle login-related features 😭 
I recommend you to consider [react-facebook](https://www.npmjs.com/package/react-facebook) instead of this library

Thank you for the good question. have a nice day :)
