### ISSUE TITLE
Overriding current access token | Error

### ISSUE THREAD

**Issue by martinabenedettofb** [greatSumini/react-facebook-login#419]
Hello, I'm encountering the following error after clicking the Facebook Login button. Just a basic implementation as suggested in the docs. The popup opens and closes immediately.

Any ideas?

Thanks a lot.

`You are overriding current access token, that means some other app is expecting different access token and you will probably break things. Please consider passing access_token directly to API parameters instead of overriding the global settings.`

**Comment by greatSumini** [comment]
Thanks for report, @martinabenedettofb 

As far as I search, this problem occurs for a variety of reasons.
It seems to happen even if you request an unauthorized scope, or if you set the Whitelist IP incorrectly.
I think it can be solved by checking the settings carefully 🥲

**Comment by greatSumini** [comment]
close this issue because it is related to Facebook sdk rather than library.

https://developers.facebook.com/community/threads/680742385690883/
