### ISSUE TITLE
How to logout once we are logged in?

### ISSUE THREAD

**Issue by mekdie** [greatSumini/react-facebook-login#422]
I just saw that you are improving the original react-facebook-login by keppelen. However, do you know how to implement logout in this case? I do not found any solution on it

**Comment by mekdie** [comment]
Also, after I logged in, when I refresh the page,  the session is not maintained (as if it is no logged in) even though in the sessionStorage there is still a logged in data

**Comment by mekdie** [comment]
> I just saw that you are improving the original react-facebook-login by keppelen. However, do you know how to implement logout in this case? I do not found any solution on it

Actually I just found a solution by playing around with session storage and local storage. Is that how it supposed to be? Sorry if I ask a lot i'm still new to react HAHA xoxo

**Comment by greatSumini** [comment]
You can use [`FacebookLoginClient.logout`](https://github.com/greatSumini/react-facebook-login#facebookloginclient)
I recommend you to generate your own token by authResponse, and save it to cookie/localstorage 😃

**Comment by mekdie** [comment]
Awesome ! I did not see that. You are simply amazing and actually improving the original react-facebook-login dependencies. Good work. Kindly check my simple implementation based on your improved TS react-facebook-login. (github.com/mekdie/react-facebook-login)

 Good TS btw :)

**Comment by greatSumini** [comment]
It’s great! Thanks for interest ☺️ Have a nice day :)
