### ISSUE TITLE
error show if logout after reload page

### ISSUE THREAD

**Issue by kien-pham** [greatSumini/react-facebook-login#5]
Current I got this issue, after login, then reload the page, and next logout. I got below error. If not reload, it works fine. How can I fix it? 

![Screen Shot 2021-08-15 at 10 00 38 PM](https://user-images.githubusercontent.com/43236511/129482901-d772c9f9-4fa6-4bbb-9e38-70c9a59d3333.png)

**Comment by greatSumini** [comment]
It seem's like a bug. I will fix it shortly! Plz wait few hours 😃

**Comment by greatSumini** [comment]
Thank you for interest & waiting. I fixed the bug v2.1.1!
