### ISSUE TITLE
React Depedency Github build fails

### ISSUE THREAD

**Issue by nmanikandan2016** [greatSumini/react-facebook-login#870]
I'm still facing this issue "While resolving: react-facebook-login@4.1.1 Found: react@18.2.0
npm ERR! node_modules/react
npm ERR! react@"^18.2.0" from the root project" I tried all the solutions mentioned in the "https://github.com/keppelen/react-facebook-login/issues/320", including installing your lib,  github does not build without errors, local project is working fine, any help is much appreciated.

**Comment by greatSumini** [comment]
fixed in new version. sorry for late fix 😅
https://github.com/greatSumini/react-facebook-login/releases/tag/v3.4.0
